### ISSUE TITLE
Command failed: vagrant status (or any other command) on Windows

### ISSUE THREAD

**Issue by mloskot** [bbenoist/vscode-vagrant#17]
I'm using the latest versions of

- Vagrant 2.2.6
- VSCode 1.39.2
- Vagrant extension 0.5.0

on Windows 10.

I open folder with simplest `Vagrantfile` in VSCode:

```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1710"
end
```

I run `Vagrant: Status` from the command palette and I'm getting this in the VSCode `Log (Window)`:

```
[2019-10-18 12:47:12.579] [renderer1] [error] Command failed: vagrant --no-color status --machine-readable
: Error: Command failed: vagrant --no-color status --machine-readable

	at ChildProcess.exithandler (child_process.js:299:12)
	at ChildProcess.emit (events.js:182:13)
	at maybeClose (internal/child_process.js:962:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
[2019-10-18 12:50:15.055] [renderer1] [error] Command failed: vagrant --no-color status --machine-readable
: Error: Command failed: vagrant --no-color status --machine-readable

	at ChildProcess.exithandler (child_process.js:299:12)
	at ChildProcess.emit (events.js:182:13)
	at maybeClose (internal/child_process.js:962:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

Running VSCode as Administrator makes no difference.

**Comment by bbenoist** [comment]
Looks like it's the same problem than #16 which has been opened just 2 hours ago. 

Did you update something recently (vscode, windows or vagrant) ?

**Comment by mloskot** [comment]
@bbenoist I searched through the existing issues...sorry, but I would have not linked that poorly titled/described issue in 1000 days :-)

> Did you update something recently (vscode, windows or vagrant) ?

Bingo! I have upgraded vagrant from 2.2.4 to 2.26

**Comment by michaelsmoody** [comment]
Good evening,

I was wondering when/if anyone has figured out what is needed to make this work with a newer version of Vagrant, and why it may not be working?
